name: abtest-ml
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        container: docker://ghcr.io/iterative/cml:0-dvc2-base1
        steps:
            - uses: actions/checkout@v2
            - name: Train model
              env:
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cml ci --unshallow
                  pip install -r requirements.txt  # Install dependencies
                  #dvc repro                        # Reproduce pipeline
            - name: Write CML report
              env:
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cat data/test.csv >> report.md
                  cml send-comment report.md
